// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8m2GgNLkJk4_c8dOQFWMAyQBj9bZjYqA',
    appId: '1:935183275161:web:1256850ef3c75c10041408',
    messagingSenderId: '935183275161',
    projectId: 'todo-app-3e965',
    authDomain: 'todo-app-3e965.firebaseapp.com',
    storageBucket: 'todo-app-3e965.appspot.com',
    measurementId: 'G-PCQX2N91V6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP4lhScT2Jd65ERKGHNOw3cTpZV-JYz2k',
    appId: '1:935183275161:ios:c15649fc17c376d0041408',
    messagingSenderId: '935183275161',
    projectId: 'todo-app-3e965',
    storageBucket: 'todo-app-3e965.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8m2GgNLkJk4_c8dOQFWMAyQBj9bZjYqA',
    appId: '1:935183275161:web:cc58d806486d63bb041408',
    messagingSenderId: '935183275161',
    projectId: 'todo-app-3e965',
    authDomain: 'todo-app-3e965.firebaseapp.com',
    storageBucket: 'todo-app-3e965.appspot.com',
    measurementId: 'G-BC84SEES10',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP4lhScT2Jd65ERKGHNOw3cTpZV-JYz2k',
    appId: '1:935183275161:ios:c15649fc17c376d0041408',
    messagingSenderId: '935183275161',
    projectId: 'todo-app-3e965',
    storageBucket: 'todo-app-3e965.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU1HFX-2RZxe4_PHteaLoYZmgR4w89z40',
    appId: '1:935183275161:android:0f860e2411228802041408',
    messagingSenderId: '935183275161',
    projectId: 'todo-app-3e965',
    storageBucket: 'todo-app-3e965.appspot.com',
  );

}